name: sam10
channels:
  - defaults
  - conda-forge
dependencies:
  - jupyter=1.0
  - jupyterlab=3.6
  - matplotlib=3.7
  - numpy=1.24
  - pip
  - pandas=1.5
  - python=3.10
  - scikit-learn=1.2
  - scipy=1.10
  - pip:
    - contextily==1.3.0
    - geopandas==0.12.2
    - flake8==6.0.0
    - mapclassify==2.5.0
    - pycodestyle_magic==0.5
    - pylatex==1.4.1
    - shap==0.41.0
    - simpy==4.0.1
    - tensorflow==2.12.0
    - xgboost==1.7.5
